-- Author:		Юрчук Жанна
-- Create date: 13.05.2008
-- Description:	Для отчета Текущая загрузка склада (сводный отчет) часть 7, который
-- выводит всю необходимую информацию для принятия управленческих решений
-- =============================================
ALTER PROCEDURE [dbo].[rep_ZCurrentCapacityWarehouse7] 
	@wh VarChar(30)
AS
BEGIN
	set @wh = upper(@wh)
	declare @sql varchar(max)
	set @sql = 'SELECT CONVERT(VARCHAR(10),ADDDATE,102) AS TODAY, ''1.    Резерв'' AS TYPE
     , COUNT(DISTINCT CASE WHEN STATUS >= 5 THEN SERIALKEY ELSE 0 END) AS TASKS
     , COUNT(DISTINCT CASE WHEN STATUS < 5 THEN SERIALKEY ELSE 0 END) AS TASKS1
  FROM '+@wh+'.PICKDETAIL (NOLOCK)
  WHERE ADDDATE > convert(datetime, convert(char(8), GetDate(), 112), 112)
  GROUP BY CONVERT(VARCHAR(10),ADDDATE,102) 
UNION
SELECT CONVERT(VARCHAR(10),'+@wh+'.ITRN.EFFECTIVEDATE,102)AS TODAY, ''2.      Отбор'' AS TYPE
     , COUNT(DISTINCT CASE WHEN '+@wh+'.PICKDETAIL.DROPID <> '''' THEN '+@wh+'.PICKDETAIL.SERIALKEY ELSE 0 END) AS TASKS
     , COUNT(DISTINCT CASE WHEN '+@wh+'.PICKDETAIL.DROPID = '''' THEN '+@wh+'.PICKDETAIL.SERIALKEY ELSE 0 END) AS TASKS1
  FROM '+@wh+'.ITRN (NOLOCK) INNER JOIN  '+@wh+'.PICKDETAIL (NOLOCK) 
    ON '+@wh+'.ITRN.SOURCEKEY = '+@wh+'.PICKDETAIL.PICKDETAILKEY
  WHERE	'+@wh+'.ITRN.EFFECTIVEDATE > convert(datetime, convert(char(8), GetDate(), 112), 112)
  GROUP BY CONVERT(VARCHAR(10),'+@wh+'.ITRN.EFFECTIVEDATE,102)
UNION
SELECT CONVERT(VARCHAR(10),'+@wh+'.DROPIDDETAIL.ADDDATE,102) AS TODAY, ''3.Упаковка'' AS TYPE
     , COUNT(DISTINCT CASE WHEN '+@wh+'.PICKDETAIL.DROPID <> '+@wh+'.DROPIDDETAIL.DROPID 
                           THEN '+@wh+'.PICKDETAIL.SERIALKEY ELSE 0 END) AS TASKS
     , COUNT(DISTINCT CASE WHEN '+@wh+'.PICKDETAIL.DROPID =  '+@wh+'.DROPIDDETAIL.DROPID 
                           THEN '+@wh+'.PICKDETAIL.SERIALKEY ELSE 0 END) AS TASKS1
  FROM '+@wh+'.DROPIDDETAIL (NOLOCK) INNER JOIN	'+@wh+'.PICKDETAIL (NOLOCK) 
    ON '+@wh+'.PICKDETAIL.CASEID = '+@wh+'.DROPIDDETAIL.CHILDID
  WHERE '+@wh+'.DROPIDDETAIL.ADDDATE > convert(datetime, convert(char(8), GetDate(), 112), 112)
  GROUP BY CONVERT(VARCHAR(10),'+@wh+'.DROPIDDETAIL.ADDDATE,102)
UNION
SELECT CONVERT(VARCHAR(10),'+@wh+'.DROPIDDETAIL.ADDDATE,102) AS TODAY, ''4. Загрузка'' AS TYPE
     , COUNT(DISTINCT CASE WHEN STATUS=9 THEN '+@wh+'.PICKDETAIL.SERIALKEY ELSE 0 END) AS TASKS
     , COUNT(DISTINCT CASE WHEN STATUS<9 THEN '+@wh+'.PICKDETAIL.SERIALKEY ELSE 0 END) AS TASKS1
  FROM '+@wh+'.DROPIDDETAIL (NOLOCK) INNER JOIN	'+@wh+'.PICKDETAIL (NOLOCK) 
    ON '+@wh+'.PICKDETAIL.DROPID = '+@wh+'.DROPIDDETAIL.DROPID
  WHERE '+@wh+'.DROPIDDETAIL.ADDDATE > convert(datetime, convert(char(8), GetDate(), 112), 112) 
    AND '+@wh+'.DROPIDDETAIL.IDTYPE = 4
  GROUP BY CONVERT(VARCHAR(10),'+@wh+'.DROPIDDETAIL.ADDDATE,102)
UNION
SELECT CONVERT(VARCHAR(10),'+@wh+'.ORDERDETAIL.EDITDATE,102)AS TODAY, ''5.Отгрузка'' AS TYPE
     , COUNT(DISTINCT '+@wh+'.PICKDETAIL.SERIALKEY) AS TASKS
     , 0 AS TASKS1
  FROM '+@wh+'.ORDERDETAIL (NOLOCK) INNER JOIN '+@wh+'.ORDERS 
    ON '+@wh+'.ORDERDETAIL.ORDERKEY = '+@wh+'.ORDERS.ORDERKEY AND '+@wh+'.ORDERS.STATUS = 95
       INNER JOIN '+@wh+'.PICKDETAIL (NOLOCK) 
    ON '+@wh+'.ORDERDETAIL.ORDERKEY = '+@wh+'.PICKDETAIL.ORDERKEY 
   AND '+@wh+'.ORDERDETAIL.ORDERLINENUMBER = '+@wh+'.PICKDETAIL.ORDERLINENUMBER 
   AND '+@wh+'.PICKDETAIL.STATUS = 9
  WHERE '+@wh+'.ORDERDETAIL.EDITDATE > convert(datetime, convert(char(8), GetDate(), 112), 112)  
  GROUP BY	CONVERT(VARCHAR(10),'+@wh+'.ORDERDETAIL.EDITDATE,102)'
--print @sql    
exec (@sql)
END

